##  Numpy array

In [1]:
import numpy as np

In [2]:


# vector -> 1D
a = np.array([1, 2, 3])
print(a)

# matrix -> 2D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# tensor -> 3D
c = np.array([[[1, 2], [3, 4], [5, 6]]])  
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]


In [3]:
# any data type pass
# vector -> 1D
a = np.array([1, 2, 3], dtype=float)
print(a)

# matrix -> 2D
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(b)

# tensor -> 3D
c = np.array([[[1, 2], [3, 4], [5, 6]]], dtype=float)  
print(c)


[1. 2. 3.]
[[1. 2. 3.]
 [4. 5. 6.]]
[[[1. 2.]
  [3. 4.]
  [5. 6.]]]


In [4]:
# ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


In [5]:
# shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(1, 3, 2)


In [6]:
# size
print(a.size)
print(b.size)
print(c.size)

3
6
6


In [7]:
# dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)

float64
float64
float64


In [8]:
# changing dtype -> must reassign after changing
a = a.astype(np.int64)
b = b.astype(np.int64)
c = c.astype(np.int64)

# dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [9]:
# range e
print(np.arange(1, 11, 3))
# reshape
print(np.arange(1, 11).reshape(2, 5))   #means 2 row 5 col banabe


[ 1  4  7 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# zeros and ones
print(np.ones((3, 4)))
print(np.zeros((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# random number initialization
np.random.random((3, 4))

array([[0.10130756, 0.34156407, 0.50702826, 0.1897908 ],
       [0.85100381, 0.56435806, 0.24537531, 0.02166958],
       [0.11981201, 0.445864  , 0.92428958, 0.82402105]])

In [12]:
# linspace -> linear space
print(np.linspace(-10, 10, 10))  #(lower, upper, total num you want to genrate)

# identity -> for identity matrix
print(np.identity(3))


[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Working with missing values

In [ ]:
# working with missing values 
a = np.array([1,2,3,4,np.nan,6])
a
a[~np.isnan(a)]  #missing value shoraye felbe

array([1., 2., 3., 4., 6.])