### Iterating

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(16).reshape(4,4)
a3 = np.arange(27).reshape(3,3,3)

In [3]:
# loop

for i in a1:
  print(i)

for i in a2:
  print(i)

for i in a3:
  print(i)

0
1
2
3
4
5
6
7
8
9
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [4]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
