## Array operations

In [2]:
import numpy as np

In [8]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# Scaler operation -> + - * / all will work

print(a1*2)
print(a2*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [ ]:
# relational operator 
print(a1>2)
print(a2>15)


[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
# vector operation
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
