### Numpy functions

In [1]:
import numpy as np

In [2]:
a = np.random.random((3,3))
a = np.round(a*100)
print(a)


[[48. 83. 66.]
 [50. 34. 96.]
 [45. 17. 39.]]


In [3]:
# max/min/sum/prod
print(np.max(a))
print(np.sum(a))
print(np.prod(a))


# max/min/sum/prod -> each row/col
# 0->col, 1->row
print(np.max(a, axis=0))
print(np.sum(a, axis=0))
print(np.prod(a, axis=0))

96.0
478.0
1280293267968000.0
[50. 83. 96.]
[143. 134. 201.]
[108000.  47974. 247104.]


In [4]:
# mean/median/std/var

print(np.mean(a))
print(np.median(a))
print(np.std(a))    # standard deviation
print(np.var(a))    # variance

53.111111111111114
48.0
23.25914130661293
540.9876543209878


In [5]:
# dot product

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

print(np.dot(a1, a2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [6]:
# log and exponents

print(np.exp(a))

[[7.01673591e+20 1.11286375e+36 4.60718663e+28]
 [5.18470553e+21 5.83461743e+14 4.92345829e+41]
 [3.49342711e+19 2.41549528e+07 8.65934004e+16]]


#### self defined formulas math function

In [15]:
# sigmoid
def sigmoid(a):
  print(a)
  return 1/(1+np.exp(-a))

a = np.arange(10)
sigmoid(a)

[0 1 2 3 4 5 6 7 8 9]


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [16]:
# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

def mse(actual, predicted):
  return np.mean((actual-predicted)**2)

mse(actual, predicted)

485.64