### Indexing and slicing 

In [11]:
import numpy as np

In [12]:
a1 = np.arange(10)
a2 = np.arange(16).reshape(4,4)
a3 = np.arange(27).reshape(3,3,3)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [13]:
# index element
print(a1[2], a2[-3])
print(a2[1,2])
print(a3[1,0,1])   #koto number 2D, shei 2D te koto number 1D, 1D er kotoo index

2 [4 5 6 7]
6
10


In [14]:
# row / col wise
print(a1[:])
print(a2[0,:])
print(a3[1,1,:])
print(a3[1,:,:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[12 13 14]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [15]:
print(a2[1:3, 1:3])
print(a2[::2, 1::2])

print(a3[::2])
print(a3[0, 1])
print(a3[1,:,1])
print(a3[2, 1:3, 1:3])


[[ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 9 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]


#### Advanced indexing

In [24]:
# fancy indexing
a2
a2[[1,2,3]]    # 1,2,3 no row show korbe
a2[:, [1,2,3]]   # 1,2,3 no col show korbe

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [27]:
# boolean indexing
a3[a3>15]  # a3 er moddhe joto value >15 shegula list akare dibe

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [29]:
a2[(a2>5) & (a2%2==0)]

array([ 6,  8, 10, 12, 14])