### Broadcasting
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [20]:
import numpy as np

In [21]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [22]:
# different shape -> but tao adding holo
a = np.arange(6).reshape(2,3) 
a = np.arange(3).reshape(1,3) 

a+b

array([[ 6,  8, 10],
       [ 9, 11, 13]])

#### Broadcasting Rules
**1. Make the two arrays have the same number of dimensions.**

- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

ex: (3,2)-> 2D, (3)-> 1D 
then (3) becomes (1,3) -> 1 in head

**2. Make each dimension of the two arrays the same size.**
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [25]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

# hbe na karon (3)->(1,3)->(3,3) != (3,4)
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 